baseURL = ""
publishDir = "public"
languageCode = "en-us"
title = "TellFinder @ Hack 4 Freedom"
theme = "kube"
description = ""
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "TellFinder Support" # add your company name
  github = "https://github.com/danismalls/TF_hack4freedom" # add your github profile name
  twitter = "" # add your twitter profile
  email = "support@tellfinder.com"

[[menu.main]]
    name = "Docs"
    weight = -200
    url = "/docs/"

[[menu.main]]
    name = "Contact The Team"
    weight = -100
    url = "/support/"
